/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_abqappthu_ttt_NeuralNet */

#ifndef _Included_com_abqappthu_ttt_NeuralNet
#define _Included_com_abqappthu_ttt_NeuralNet
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_abqappthu_ttt_NeuralNet
 * Method:    jniCreateNeuralNet
 * Signature: (III)V
 */
JNIEXPORT jint JNICALL Java_com_abqappthu_ttt_NeuralNet_jniCreateNeuralNet
  (JNIEnv *, jobject, jint, jint, jint);

JNIEXPORT void JNICALL Java_com_abqappthu_ttt_NeuralNet_jniDestroyNeuralNet
(JNIEnv *, jobject, jint);

/*
 * Class:     com_abqappthu_ttt_NeuralNet
 * Method:    jniSetTestWeights
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_abqappthu_ttt_NeuralNet_jniSetTestWeights
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_abqappthu_ttt_NeuralNet
 * Method:    jniSetTestBiases
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_abqappthu_ttt_NeuralNet_jniSetTestBiases
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_abqappthu_ttt_NeuralNet
 * Method:    jniFeedForward
 * Signature: ([F[F)V
 */
JNIEXPORT void JNICALL Java_com_abqappthu_ttt_NeuralNet_jniFeedForward
  (JNIEnv *, jobject, jint, jfloatArray, jfloatArray);

/*
 * Class:     com_abqappthu_ttt_NeuralNet
 * Method:    SGD
 * Signature: ([F[FIIF)V
 */
JNIEXPORT void JNICALL Java_com_abqappthu_ttt_NeuralNet_jniSGD
  (JNIEnv *, jobject, jint, jfloatArray, jfloatArray, jint, jint, jint, jfloat);

/*
 * Class:     com_abqappthu_ttt_NeuralNet
 * Method:    getWeight
 * Signature: (III)F
 */
JNIEXPORT jfloat JNICALL Java_com_abqappthu_ttt_NeuralNet_jniGetWeight
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     com_abqappthu_ttt_NeuralNet
 * Method:    getBias
 * Signature: (II)F
 */
JNIEXPORT jfloat JNICALL Java_com_abqappthu_ttt_NeuralNet_jniGetBias
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     com_abqappthu_ttt_NeuralNet
 * Method:    getNinput
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_abqappthu_ttt_NeuralNet_jniGetNinput
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_abqappthu_ttt_NeuralNet
 * Method:    getNhidden
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_abqappthu_ttt_NeuralNet_jniGetNhidden
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_abqappthu_ttt_NeuralNet
 * Method:    getNoutput
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_abqappthu_ttt_NeuralNet_jniGetNoutput
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
